@echo off

echo No need to run the file, no effect taked.
goto NO_EFFECT
echo #pragma once > common.hpp

echo // Do Not edit this file manual, please run make.bat >> common.hpp


for %%f in (*.h) do @echo #include "%%f" >> common.hpp

:NO_EFFECT
pause